### PR TITLE
grc.conf : command ip and traceroute :

### PR DESCRIPTION
**Pull request by Raizo62**
- accept parameters between "ip" and main parameter
	- accept all correct syntax of "address" ("a", "ad", "add", "addr", "addre",...,"address")
	- do the the same with "link", "route" and "neighbour"

### CODE REVIEW

**Comment by Mic92** [comment]
actually ip has its own color support now.

**Comment by Raizo62** [comment]
@Mic92  you are right : 
`ip -c=auto a`
Thanks

**Comment by luisdavim** [comment]
this can still be useful for mac users that use https://github.com/brona/iproute2mac that doesn't support colour.

**Comment by luisdavim** [comment]
oh, this PR seems to be about `traceroute` and the other one with the same name (#132) is the one about `ip` can you update the PR title?

**Pull request merged**
