### PR TITLE
Add more commands, fix colors to selected current ones.

### PR DESCRIPTION
**Pull request by iax7**

### CODE REVIEW

**Comment by derimagia** [comment]
For the docker ones, take a look at #27 (Although you have more commands, we should probably merge them)

**Comment by garabik** [comment]
Sorry for the delay - life was just getting in the way.

I merged the commits manually and tried to include both docker pull requests  - the colours might be inconsistent, though. Since I do not use docker, I do not have means to test it properly.

**Comment by derimagia** [comment]
Nice! A few comments/missing things:

IPs/Ports are listed twice currently for docker.ps, here's a screenshot for you to compare the two: https://i.imgur.com/7lMhMxT.png

Headers are listed twice, I'd just the top one as it takes care of docker-compose as well.

Exited Status can change to:
```
# Statuses - Exited
regexp=\sExit(ed)?(?:\s\(\d\)?)?(.*)\s
colours=concealed red
```

since that would take care of docker-compose

In docker-compose ps, I couldn't think of how to match the docker ps with the command since it doesn't quote: https://i.imgur.com/f1AuD6B.png

Looks like my docker images changes were missed:

https://github.com/garabik/grc/pull/27/commits/6f6ef83a9092b907016c8ff8de1730e50ee62469

If you want me to put all of this in a new pull request let me know :)

**Comment by garabik** [comment]
> If you want me to put all of this in a new pull request let me know :)

That would save me some time, so if it's not a problem, I'd be happy to receive the pull request

**Pull request merged**
